### ISSUE TITLE
Elaboration on "Custom Firmware"

### ISSUE THREAD

**Issue by Ninjawarrior81** [hrydgard/ppsspp-site#19]
docs/getting-started/dumping-games.md
The link above said that one of the prerequisites is a PSP with custom firmware. As someone new to the whole concept, it wasn't clear to me where or which firmware exactly I should download. 
I found this website, which I assume is what I'm meant to download (https://www.pspunk.com/psp-cfw/).

**Comment by hrydgard** [comment]
I intentionally haven't linked anything because I don't have the time to keep up with the custom firmware scene - i've installed once on my PSPs years ago and then just left it. That said, the custom firmware scene is probably fairly static these days, so an argument can certainly be made to link some things.
