### ISSUE TITLE
Expose Atom/RSS Feeds

### ISSUE THREAD

**Issue by ReillyBrogan** [hrydgard/ppsspp-site#20]
Docusaurus generates an RSS/Atom feed by default ([ref](https://docusaurus.io/docs/blog#feed)), so there are valid RSS/Atom feeds for the news and blog at `https://www.ppsspp.org/news/rss.xml`  and `https://www.ppsspp.org/blog/rss.xml` respectively (replace `rss.xml` with `atom.xml` for the atom version). There is no indication however that these exist, so it would be great if you could add an RSS icon to the news and blog sections with the link to the respective feed (I would just link to the atom feed over the RSS feed personally). 

Additionally, though RSS/Atom clients don't really care about this, it would be best practice to set the Atom feed content-type to `application/atom+xml` so the browser doesn't try to render it.

**Comment by hrydgard** [comment]
Good suggestion - I'm surprised Docusaurus doesn't do this automatically. I've been a bit disappointed overall with Docusaurus as a framework for making some things that should be easy really really hard, heh. I'm not sure how to best inject this link without doing one of those swizzle operations.

PRs accepted, btw :)

**Comment by hrydgard** [comment]
I threw out docusaurus because to me, it was too hard to work with. Had to re-learn it every time I wanted to change something.

So now the whole site is vanilla JS, html and css, with handlebars template driven by a very basic static site generator written in Rust :)

So, went ahead and added this to the left sidebar of the blogs, though considering alternate placements.
